name: "Mac's Marvelous Master Key Experience"
favicon: null
layout_spectrum: 0.8845256865024567
typography_spectrum: 0.15815706853754818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5452352969441563
  lightness: 0.48723389278165996
  saturation: 0.8779424144886434
  rhythmicContrast: 0.20630121254362166
purpose: []
